/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.ui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.dto.ExamenAsignadoDTO;
import modelo.dto.ExamenAsignadoPK;
import modelo.dto.UsuarioDTO;
import vista.controlador.CVContestarExamen;
import vista.controlador.RespaldoJSON;
import vista.interfaz.InterfaceVista;

/**
 *
 * @author Alf
 */
public class VistaBuscarExamenAsignado extends javax.swing.JPanel implements
        InterfaceVista {

    private static final int HOLGURA = 1000 * 30;
    private InterfaceVista padre;
    private CVContestarExamen control;
    private DefaultListModel dlm;
    private final RespaldoJSON respaldo;

    /**
     * Creates new form VistaBuscarExamenAsignado
     */
    public VistaBuscarExamenAsignado() {
        initComponents();
        lstExamenesEncontrados.setModel(new DefaultListModel());
        lstExamenesEncontrados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        dlm = (DefaultListModel) lstExamenesEncontrados.getModel();
        respaldo = new RespaldoJSON();
    }

    public void setPadre(InterfaceVista padre) {
        this.padre = padre;
    }

    public void setControlador(CVContestarExamen cvContestarExamen) {
        this.control = cvContestarExamen;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstExamenesEncontrados = new javax.swing.JList();
        btnIniciar = new javax.swing.JButton();

        setName(""); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Buscar Examen");

        btnBuscar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setPreferredSize(new java.awt.Dimension(73, 30));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstExamenesEncontrados);

        btnIniciar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnIniciar.setText("Iniciar");
        btnIniciar.setPreferredSize(new java.awt.Dimension(65, 30));
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(358, 358, 358))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(238, 238, 238))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblTitulo)
                .addGap(43, 43, 43)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        limpiar();
        if (respaldo.existeRespaldo()) {

            ArrayList alumno = respaldo.getRespaldo();
            ExamenAsignadoPK eapk = (ExamenAsignadoPK) alumno.get(RespaldoJSON.I_EXAMEN_ASIGNADO_PK);
            control.setExamenAsignado(eapk);
            ExamenAsignadoDTO examen = control.obtenerExamenAsignado();
            long inicio = examen.getFechaAsignacion().getTime();
            long fin = inicio + (examen.getTiempo() * 60 * 1000);
            boolean usuarioRespaldo = padre.obtenerUsuarioActual().getId() == eapk.getIdAlumno();
            boolean contestado = respaldo.estaContestado();

            if (contestado && usuarioRespaldo) {
                JOptionPane.showMessageDialog(this, "Tienes un examen pendiente "
                        + "por enviar." + "\n" + "Reenviando",
                        "Respaldo examen", JOptionPane.INFORMATION_MESSAGE);
                calificarExamen(examen, alumno);
                respaldo.eliminarRespaldo();
            } else if (usuarioRespaldo && System.currentTimeMillis() < (fin + HOLGURA) && !contestado) {
                int ok = JOptionPane.showConfirmDialog(this, "Desea continuar "
                        + "con el examen pendiente", "Respaldo", JOptionPane.YES_NO_OPTION);
                if (ok == JOptionPane.YES_OPTION) {
                    padre.mostrarVistaConEntidad(respaldo, Vista.ContestarExamen);
                    limpiar();
                }
            } else if (usuarioRespaldo && System.currentTimeMillis() > (fin + HOLGURA) && !contestado) {
                calificarExamen(examen, alumno);
                respaldo.eliminarRespaldo();
            } else if (!usuarioRespaldo) {
                control.calificarExamen(examen.getReactivos().size(),
                        (List<String>) alumno.get(RespaldoJSON.I_RESPUESTAS), examen);
                control.actualizarExamen(examen);
                respaldo.eliminarRespaldo();
            }
        }
        //no hay respaldo o no desea continuar con su examen anterior
        List<ExamenAsignadoDTO> ea;
        ea = control.obtenerExamenesAsignados(padre.obtenerUsuarioActual());
        if (ea.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Examenes no asignados");
        } else {
            for (ExamenAsignadoDTO examen : ea) {
                dlm.addElement(examen.getExamen().getTitulo());
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void calificarExamen(ExamenAsignadoDTO examen, ArrayList alumno) {
        double calificacion = control.calificarExamen(examen.getReactivos().size(),
                (List<String>) alumno.get(RespaldoJSON.I_RESPUESTAS), control.obtenerExamenAsignado());
        String cali = String.format("%.2f", calificacion);
        if (calificacion == 100) {
            JOptionPane.showMessageDialog(this, "Su calificación es de: " + cali,
                    "Calificación", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/recursos/like.png")));
        } else {
            JOptionPane.showMessageDialog(this, "Su calificación es de: "
                    + cali, "Calificación", JOptionPane.INFORMATION_MESSAGE);
        }

        if (control.actualizarExamen(control.obtenerExamenAsignado())) {
            respaldo.eliminarRespaldo();
        } else {
            JOptionPane.showMessageDialog(this, "Exmen no actualizado");
        }
    }

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        int index = lstExamenesEncontrados.getSelectedIndex();
        if (index != -1) {
            ExamenAsignadoPK expk = control.obtenerExamenesAsignados(padre.obtenerUsuarioActual()).get(index).getId();
            control.setExamenAsignado(expk);
            padre.mostrarVistaConEntidad(expk, Vista.ContestarExamen);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un examen");
        }
        limpiar();
    }//GEN-LAST:event_btnIniciarActionPerformed

    @Override
    public void mostrarVistaConEntidad(Object entidad, Vista vista) {
        //
    }

    @Override
    public void mostrarVista(Vista vista) {
        //
    }

    @Override
    public void mostrarEntidad(Object entidad) {
        //
    }

    @Override
    public boolean confirmarCambio() {
        return true;
    }

    @Override
    public UsuarioDTO obtenerUsuarioActual() {
        return padre.obtenerUsuarioActual();
    }

    @Override
    public void limpiar() {
        dlm.setSize(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList lstExamenesEncontrados;
    // End of variables declaration//GEN-END:variables

}
