/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.ui;

import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.BorderFactory;
import javax.swing.JTextField;
import javax.swing.border.Border;
import modelo.dto.UsuarioDTO;
import vista.controlador.CVLogin;
import vista.controlador.Validador;

/**
 *
 * @author Jesus Donaldo
 */
public class VistaLogin extends javax.swing.JFrame implements FocusListener {

    FrmPrincipal p;
    private CVLogin cvLogin;
    private final Border BORDE_ORIGINAL;
    private final Border BORDE_MAL;

    /**
     * Creates new form VistaLogin
     */
    public VistaLogin() {
        initComponents();
        p = new FrmPrincipal();
        BORDE_ORIGINAL = txtfUsuario.getBorder();
        BORDE_MAL = BorderFactory.createLineBorder(Color.red);
        cvLogin = new CVLogin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        txtfUsuario = new javax.swing.JTextField();
        txtfUsuario.addFocusListener(this);
        lblUsuario = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtpPassword = new javax.swing.JPasswordField();
        txtpPassword.addFocusListener(this);
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 370));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 370));

        btnLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin(evt);
            }
        });

        txtfUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtfUsuario.setPreferredSize(new java.awt.Dimension(100, 30));

        lblUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblUsuario.setText("Usuario:");

        lblPassword.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPassword.setText("Password:");

        txtpPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtpPassword.setPreferredSize(new java.awt.Dimension(100, 25));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setText("Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(lblTitulo))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(lblUsuario)
                .addGap(104, 104, 104)
                .addComponent(txtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(lblPassword)
                .addGap(90, 90, 90)
                .addComponent(txtpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(412, 412, 412)
                .addComponent(btnLogin))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblTitulo)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblUsuario))
                    .addComponent(txtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblPassword))
                    .addComponent(txtpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin
//        UsuarioDTO usuario;
//        usuario = encapsularUsuario();
//        if (usuario == null) {
//            JOptionPane.showMessageDialog(this, "Datos incorrectos, porfavor "
//                    + "sólo ingresa números y letras");
//        } else {
//            int error = cvLogin.validarCredenciales(usuario);
//            if (error == -1) {
//                UsuarioDTO usuarioValido = cvLogin.obtenerUsuarioValidado();
//                JOptionPane.showMessageDialog(this, "Bienvenido "
//                        + usuarioValido.getNombre());
//                p.setUsuarioActual(usuarioValido);
//                Tipo tipo = usuarioValido.getTipo();
//                if (tipo == Tipo.Admin) {
        p.setVistaAdmin();
//                } else if (tipo == Tipo.Alumno) {
//                    p.setVistaAlumno();
//                } else if (tipo == Tipo.Maestro) {
//                    p.setVistaMaestro();
//                }
        p.setVisible(true);
        dispose();
//            } else if (error == 1) {
//                JOptionPane.showMessageDialog(this, "Password Incorrecto");
//            } else {
//                JOptionPane.showMessageDialog(this, "Usuario no existente");
//            }
//
//        }

    }//GEN-LAST:event_btnLogin

    private UsuarioDTO encapsularUsuario() {
        UsuarioDTO usuario = new UsuarioDTO();

        String pass = String.valueOf(txtpPassword.getPassword());
        String usuari = txtfUsuario.getText();
        boolean ok = true;

        if (!Validador.esPassword(pass)) {
            txtpPassword.setBorder(BORDE_MAL);
            ok = false;
        } else {
            txtpPassword.setBorder(BORDE_ORIGINAL);
        }

        if (!Validador.esUsuario(usuari)) {
            txtfUsuario.setBorder(BORDE_MAL);
            ok = false;
        } else {
            txtfUsuario.setBorder(BORDE_ORIGINAL);
        }

        usuario.setPassword(pass);
        usuario.setUsuario(usuari);

        if (!ok) {
            usuario = null;
        }

        return usuario;
    }

    @Override
    public void focusGained(FocusEvent e) {
        ((JTextField) e.getSource()).setBorder(BORDE_ORIGINAL);
    }

    @Override
    public void focusLost(FocusEvent e) {
        if (e.getSource() == txtfUsuario) {
            if (!Validador.esUsuario(txtfUsuario.getText())) {
                txtfUsuario.setBorder(BORDE_MAL);
            } else {
                txtfUsuario.setBorder(BORDE_ORIGINAL);
            }
        } else if(e.getSource() == txtpPassword){
            if (!Validador.esPassword(String.valueOf(txtpPassword.getPassword()))) {
                txtpPassword.setBorder(BORDE_MAL);
            } else {
                txtpPassword.setBorder(BORDE_ORIGINAL);

            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                
                if("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
                //UIManager.setLookAndFeel("com.seaglasslookandfeel.SeaGlassLookAndFeel");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtfUsuario;
    private javax.swing.JPasswordField txtpPassword;
    // End of variables declaration//GEN-END:variables

}
